version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "{POSTGRES_PASSWORD}"
    user: "${UID}:${GID}" 
  api:
    build: .
    ports:
      - 80:80
    environment:
      POSTGRES_PASSWORD: "{POSTGRES_PASSWORD}"
      SECRET_KEY: "{SECRET_KEY}"