version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: mysecret
    user: 1000:1000 
  api:
    build: .
    ports:
      - 80:80